export const initialMenuItems = [
  // FOOD - SIGNATURES & MAINS
  {
    name: "Mangalorean Chicken Ghee Roast",
    description: "Tender morsels of chicken tossed in stone-ground Kundapur spices, pure clarified butter, roasted curry leaves, served on soft neer dosa.",
    category: "Food",
    subCategory: "signatures",
    price: 645,
    dietary: "non-veg",
    featured: true,
    isChefsSpecial: true,
    isGlutenFree: true,
    spiciness: 2,
    pairWith: "Mumbai Mule or Smoked Old Fashioned",
    image: "/images/food/mangalorean-chicken-ghee-roast.jpg",
    tags: ["Legendary", "Coastal", "Chef Signature"],
    available: true
  },
  {
    name: "Truffle Edamame & Wild Mushroom Dimsum",
    description: "Translucent crystal parcels filled with charred forest mushrooms, edamame paste, infused with black winter truffle oil and chili scallion dip.",
    category: "Food",
    subCategory: "signatures",
    price: 595,
    dietary: "veg",
    featured: true,
    isChefsSpecial: true,
    isGlutenFree: false,
    spiciness: 1,
    pairWith: "Sunset Botanist Gin Tonic",
    image: "https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?auto=format&fit=crop&w=800&q=80",
    tags: ["Artisanal", "Bestseller", "Vegetarian"],
    available: true
  },
  {
    name: "Lion Chicken Tenders with Peri-Peri Glaze",
    description: "1522's legendary crispy chicken supreme tenders, double-breaded in artisanal crumb, tossed in zesty peri-peri glaze, house garlic ranch.",
    category: "Food",
    subCategory: "signatures",
    price: 545,
    dietary: "non-veg",
    featured: true,
    isChefsSpecial: true,
    isGlutenFree: false,
    spiciness: 2,
    pairWith: "Cold Craft IPA or Jamun Gin Fizz",
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80",
    tags: ["Bar Classic", "1522 Favorite"],
    available: true
  },
  {
    name: "Truffled Funghi & Fior di Latte Pizza",
    description: "48-hour fermented sourdough crust, San Marzano tomato sauce, wild porcini & button mushrooms, fior di latte mozzarella, black truffle drizzle.",
    category: "Food",
    subCategory: "wood-fired-pizza",
    price: 675,
    dietary: "veg",
    featured: true,
    isChefsSpecial: true,
    isGlutenFree: false,
    spiciness: 0,
    pairWith: "Chianti Classico",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80",
    tags: ["Artisanal Sourdough", "Wood-Fired", "Chef Signature"],
    available: true
  },
  {
    name: "Quattro Formaggi & Hot Honey Pizza",
    description: "Smoked scamorza, gorgonzola dolce, aged parmesan, fior di latte, cold-pressed chili honey drizzle, and toasted walnuts on slow-fermented crust.",
    category: "Food",
    subCategory: "wood-fired-pizza",
    price: 695,
    dietary: "veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: false,
    spiciness: 1,
    pairWith: "Craft IPA or Pinot Grigio",
    image: "https://images.unsplash.com/photo-1573821663912-569905455b1c?auto=format&fit=crop&w=800&q=80",
    tags: ["Four Cheese", "Artisanal Crust"],
    available: true
  },
  {
    name: "Burrata Caprese & Basil Pesto Pizza",
    description: "Whole artisanal burrata heart, San Marzano sauce, heirloom cherry tomatoes, cold-pressed Genovese basil pesto, toasted pine nuts.",
    category: "Food",
    subCategory: "wood-fired-pizza",
    price: 725,
    dietary: "veg",
    featured: true,
    isChefsSpecial: true,
    isGlutenFree: false,
    spiciness: 0,
    pairWith: "Sunset Botanist Gin Tonic",
    image: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&w=800&q=80",
    tags: ["Fresh Burrata", "Chef Special"],
    available: true
  },
  {
    name: "Smoked Pepperoni & Spiced Nduja Pizza",
    description: "Imported slow-cured pork pepperoni, spicy Calabrian nduja sausage, San Marzano tomatoes, fresh mozzarella, oregano, hot pepper flakes.",
    category: "Food",
    subCategory: "wood-fired-pizza",
    price: 745,
    dietary: "non-veg",
    featured: true,
    isChefsSpecial: false,
    isGlutenFree: false,
    spiciness: 2,
    pairWith: "Smoked Old Fashioned or Belgian Ale",
    image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=800&q=80",
    tags: ["Classic Pepperoni", "Spicy Nduja"],
    available: true
  },
  {
    name: "Coastal Butter Garlic Prawns Pizza",
    description: "Butter-poached Arabian Sea tiger prawns, confit garlic, fresh mozzarella, capers, bird's eye chili flakes, and torn peppery arugula leaves.",
    category: "Food",
    subCategory: "wood-fired-pizza",
    price: 775,
    dietary: "non-veg",
    featured: false,
    isChefsSpecial: true,
    isGlutenFree: false,
    spiciness: 1,
    pairWith: "Crisp Sauvignon Blanc",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=800&q=80",
    tags: ["Seafood", "Coastal Twist"],
    available: true
  },
  {
    name: "Charred Tandoori Paneer & Bell Pepper Pizza",
    description: "Spiced malai paneer cubes, San Marzano base, smoked bell peppers, sun-dried tomatoes, fior di latte, and fresh cilantro drizzle.",
    category: "Food",
    subCategory: "wood-fired-pizza",
    price: 625,
    dietary: "veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: false,
    spiciness: 1,
    pairWith: "Basmati Blonde Ale",
    image: "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&w=800&q=80",
    tags: ["Tandoor Fusion", "Vegetarian"],
    available: true
  },
  {
    name: "Koliwada Prawns Crisp Bowl",
    description: "Fresh Arabian Sea tiger prawns marinated in coastal red pepper paste, ajwain, fried golden with green chutney drizzle and lemon wedges.",
    category: "Food",
    subCategory: "starters",
    price: 725,
    dietary: "non-veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: true,
    spiciness: 2,
    pairWith: "Crisp Sauvignon Blanc",
    image: "/images/food/koliwada-prawns.png",
    tags: ["Seafood", "Mumbai Street Classic"],
    available: true
  },
  {
    name: "Malabar Pepper Calamari Rings",
    description: "Tender calamari tossed with cracked Tellicherry black pepper, curry leaves, crushed shallots, and spicy kokum dip.",
    category: "Food",
    subCategory: "starters",
    price: 685,
    dietary: "non-veg",
    featured: true,
    isChefsSpecial: false,
    isGlutenFree: true,
    spiciness: 2,
    pairWith: "Chilled Witbier or Sauvignon Blanc",
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80",
    tags: ["Coastal Classic", "Seafood"],
    available: true
  },
  {
    name: "Charred Bhatti Murgh Tikka",
    description: "Boneless chicken thighs marinated overnight in dark roasted spices, mustard oil, and hung curd, charred to perfection in clay tandoor.",
    category: "Food",
    subCategory: "starters",
    price: 575,
    dietary: "non-veg",
    featured: false,
    isChefsSpecial: true,
    isGlutenFree: true,
    spiciness: 2,
    pairWith: "Cold IPA or Mumbai Mule",
    image: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=800&q=80",
    tags: ["Tandoor", "Bar Favorite"],
    available: true
  },
  {
    name: "Gunpowder Baby Potatoes with Ghee",
    description: "Crispy baby potatoes tossed in aromatic South Indian podi spice powder, curry leaves, and pure golden clarified butter.",
    category: "Food",
    subCategory: "starters",
    price: 445,
    dietary: "veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: true,
    spiciness: 1,
    pairWith: "Craft Lager",
    image: "https://images.unsplash.com/photo-1518013034458-30b0ee243591?auto=format&fit=crop&w=800&q=80",
    tags: ["Vegetarian", "South Indian"],
    available: true
  },
  {
    name: "Malai Broccoli with Smoked Cheese",
    description: "Charcoal-grilled broccoli florets steeped in rich cashew paste, cardamom cream, and melted smoked cheddar.",
    category: "Food",
    subCategory: "starters",
    price: 495,
    dietary: "veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: true,
    spiciness: 0,
    pairWith: "Chardonnay or Botanical Spritz",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    tags: ["Vegetarian", "Tandoor Gourmet"],
    available: true
  },
  {
    name: "Dal 1522 (Slow Cooked 24 Hours)",
    description: "Whole black urad lentils slow-simmered overnight over charcoal embers, blended with cream, ripe tomatoes, and gentle aromatic spices.",
    category: "Food",
    subCategory: "mains-indian",
    price: 495,
    dietary: "veg",
    featured: true,
    isChefsSpecial: true,
    isGlutenFree: true,
    spiciness: 0,
    pairWith: "Jeera Rice & Tandoori Roti",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=80",
    tags: ["Comfort", "Iconic Heritage"],
    available: true
  },
  // ==========================================
  // INDIAN CURRIES — ROYAL POULTRY & MEATS
  // ==========================================
  {
    name: "Chicken Chaap",
    description: "Slow-cooked chicken leg steeped in rich poppy seed, mace, nutmeg, and cashew gravy.",
    category: "Food",
    subCategory: "curries-non-veg",
    price: 325,
    dietary: "non-veg",
    featured: true,
    isChefsSpecial: true,
    isGlutenFree: true,
    spiciness: 1,
    pairWith: "Mughlai Paratha or Rumali Roti",
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80",
    tags: ["Mughlai Heritage", "Chef Special"],
    available: true
  },
  {
    name: "Chicken Tikka Masala",
    description: "Charcoal-grilled chicken tikka in a spiced tomato-onion masala with roasted bell peppers.",
    category: "Food",
    subCategory: "curries-non-veg",
    price: 325,
    dietary: "non-veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: true,
    spiciness: 2,
    pairWith: "Garlic Butter Naan",
    image: "/images/food/koliwada-prawns.png",
    tags: ["Tandoori Classic", "Bestseller"],
    available: true
  },
  {
    name: "Kadai Chicken",
    description: "Tender chicken tossed with freshly pounded coriander seeds, dried red chilies, and bell peppers.",
    category: "Food",
    subCategory: "curries-non-veg",
    price: 325,
    dietary: "non-veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: true,
    spiciness: 2,
    pairWith: "Tandoori Roti",
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80",
    tags: ["North Indian", "Spiced Gravy"],
    available: true
  },
  {
    name: "Delhi Wale Butter Chicken",
    description: "Tandoori shredded chicken in a silky, rich makhani gravy infused with fenugreek and butter.",
    category: "Food",
    subCategory: "curries-non-veg",
    price: 325,
    dietary: "non-veg",
    featured: true,
    isChefsSpecial: true,
    isGlutenFree: true,
    spiciness: 1,
    pairWith: "Butter Naan",
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=800&q=80",
    tags: ["Delhi Classic", "Chef Signature"],
    available: true
  },
  {
    name: "Pista Murgh",
    description: "Royal Mughlai chicken preparation simmered in a luscious pistachio, green cardamom, and cream gravy.",
    category: "Food",
    subCategory: "curries-non-veg",
    price: 345,
    dietary: "non-veg",
    featured: false,
    isChefsSpecial: true,
    isGlutenFree: true,
    spiciness: 0,
    pairWith: "Sheermal or Saffron Rice",
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80",
    tags: ["Royal Mughlai", "Nut Rich"],
    available: true
  },
  {
    name: "Dum Ki Nalli",
    description: "Slow-cooked lamb shanks infused with potli masala, rose petals, and aromatic saffron essence.",
    category: "Food",
    subCategory: "curries-non-veg",
    price: 425,
    dietary: "non-veg",
    featured: true,
    isChefsSpecial: true,
    isGlutenFree: true,
    spiciness: 2,
    pairWith: "Khamiri Roti or Basmati Rice",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    tags: ["Slow Dum", "Awadhi Specialty"],
    available: true
  },
  {
    name: "Dungar Maas",
    description: "Fiery Rajasthani smoked mutton curry flavored with Mathania red chilies and cloves.",
    category: "Food",
    subCategory: "curries-non-veg",
    price: 425,
    dietary: "non-veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: true,
    spiciness: 3,
    pairWith: "Bajra Roti or Jeera Rice",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=80",
    tags: ["Rajasthani", "Smoked Spicy"],
    available: true
  },
  {
    name: "Hari Mirch Ki Gosht",
    description: "Succulent mutton pieces braised in a piquant green chili, coriander, and mint gravy.",
    category: "Food",
    subCategory: "curries-non-veg",
    price: 425,
    dietary: "non-veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: true,
    spiciness: 3,
    pairWith: "Laccha Paratha",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    tags: ["Green Chili", "Fiery Meat"],
    available: true
  },
  {
    name: "Murgh Rezala",
    description: "Royal Bengali-style white chicken stew with yogurt, cashew paste, whole dried red chilies, and kewra essence.",
    category: "Food",
    subCategory: "curries-non-veg",
    price: 345,
    dietary: "non-veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: true,
    spiciness: 1,
    pairWith: "Rumali Roti",
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80",
    tags: ["Awadhi White Gravy", "Kewra"],
    available: true
  },
  {
    name: "Bhuna Gosht Masaledar",
    description: "Tender mutton chunks pan-roasted in a thick onion, garlic, and freshly ground whole garam masala reduction.",
    category: "Food",
    subCategory: "curries-non-veg",
    price: 435,
    dietary: "non-veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: true,
    spiciness: 2,
    pairWith: "Tandoori Roti or Naan",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=80",
    tags: ["Bhuna Masala", "Heritage Mutton"],
    available: true
  },
  {
    name: "Raan-e-1522 (Slow Braised Lamb)",
    description: "Whole spiced lamb leg braised for 8 hours in aromatic Awadhi potli masala and rich saffron jus.",
    category: "Food",
    subCategory: "curries-non-veg",
    price: 595,
    dietary: "non-veg",
    featured: true,
    isChefsSpecial: true,
    isGlutenFree: true,
    spiciness: 2,
    pairWith: "Khamiri Roti & Single Malt",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    tags: ["Chef Masterpiece", "8-Hour Braise"],
    available: true
  },

  // ==========================================
  // REGIONAL & COASTAL CURRIES
  // ==========================================
  {
    name: "Murgh Malai Methi",
    description: "Tender chicken simmered in a creamy gravy of fresh fenugreek leaves, cream, and mild spices.",
    category: "Food",
    subCategory: "curries-coastal",
    price: 325,
    dietary: "non-veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: true,
    spiciness: 1,
    pairWith: "Tandoori Naan",
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80",
    tags: ["Fenugreek Cream", "Mild"],
    available: true
  },
  {
    name: "Saag Wala Murgh",
    description: "Classic slow-cooked chicken in farm-fresh spinach, mustard greens, and garlic tempered gravy.",
    category: "Food",
    subCategory: "curries-coastal",
    price: 325,
    dietary: "non-veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: true,
    spiciness: 1,
    pairWith: "Makki Roti or Rice",
    image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80",
    tags: ["Spinach Curry", "Heritage"],
    available: true
  },
  {
    name: "Malvani Kalimirch Chicken",
    description: "Coastal Konkan-style peppery chicken curry with roasted coconut and black pepper.",
    category: "Food",
    subCategory: "curries-coastal",
    price: 325,
    dietary: "non-veg",
    featured: true,
    isChefsSpecial: true,
    isGlutenFree: true,
    spiciness: 2,
    pairWith: "Vade or Steamed Rice",
    image: "/images/food/malvani-kalimirch-chicken.jpg",
    tags: ["Malvani", "Peppery Coconut"],
    available: true
  },
  {
    name: "Red Hot Kerala Fish Curry",
    description: "Fresh seer fish simmered in a spicy, tangy red chili and Kudampuli (Malabar tamarind) sauce.",
    category: "Food",
    subCategory: "curries-coastal",
    price: 395,
    dietary: "non-veg",
    featured: true,
    isChefsSpecial: true,
    isGlutenFree: true,
    spiciness: 3,
    pairWith: "Appam or Steamed Rice",
    image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80",
    tags: ["Kerala Seer Fish", "Kudampuli"],
    available: true
  },
  {
    name: "Mario's Mango Prawns & Coconut Rice",
    description: "Goan-style prawns simmered in a sweet & tangy raw mango coconut curry, served with coconut rice.",
    category: "Food",
    subCategory: "curries-coastal",
    price: 445,
    dietary: "non-veg",
    featured: true,
    isChefsSpecial: true,
    isGlutenFree: true,
    spiciness: 1,
    pairWith: "Steamed Coconut Rice",
    image: "/images/food/koliwada-prawns.png",
    tags: ["Goan Mango", "Coastal Prawns"],
    available: true
  },
  {
    name: "Prawn Masala",
    description: "Juicy prawns tossed in a thick, spicy coastal tomato, onion, and roasted spice masala.",
    category: "Food",
    subCategory: "curries-coastal",
    price: 425,
    dietary: "non-veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: true,
    spiciness: 2,
    pairWith: "Neer Dosa or Chapati",
    image: "/images/food/koliwada-prawns.png",
    tags: ["Coastal Masala", "Arabian Prawns"],
    available: true
  },
  {
    name: "Bombay Dabba Gosht",
    description: "Iconic Bohri-style baked mutton dish in rich spiced white gravy topped with golden egg and ghee.",
    category: "Food",
    subCategory: "curries-coastal",
    price: 425,
    dietary: "non-veg",
    featured: true,
    isChefsSpecial: true,
    isGlutenFree: false,
    spiciness: 1,
    pairWith: "Pav or Paratha",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    tags: ["Bohri Specialty", "Bombay Icon"],
    available: true
  },
  {
    name: "Mangalorean Meen Gassi",
    description: "Fresh Kingfish steaks simmered in roasted coconut, coriander, and kokum gravy.",
    category: "Food",
    subCategory: "curries-coastal",
    price: 395,
    dietary: "non-veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: true,
    spiciness: 2,
    pairWith: "Neer Dosa or Steamed Rice",
    image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80",
    tags: ["Kingfish", "Coconut Gassi"],
    available: true
  },
  {
    name: "Kori Rotti & Kundapur Chicken Curry",
    description: "Traditional crisp rice wafers drenched in rich spiced Mangalorean red chicken curry.",
    category: "Food",
    subCategory: "curries-coastal",
    price: 345,
    dietary: "non-veg",
    featured: false,
    isChefsSpecial: true,
    isGlutenFree: true,
    spiciness: 2,
    pairWith: "Crisp Kori Rotti",
    image: "/images/food/chicken-ghee-roast.jpg",
    tags: ["Kori Rotti", "Kundapur Heritage"],
    available: true
  },

  // ==========================================
  // RICE & BIRYANI
  // ==========================================
  {
    name: "Gosht Dum Biryani",
    description: "Fragrant Basmati rice slow-cooked on dum with tender spiced mutton, fried onions, and saffron.",
    category: "Food",
    subCategory: "rice-biryani",
    price: 445,
    dietary: "non-veg",
    featured: true,
    isChefsSpecial: true,
    isGlutenFree: true,
    spiciness: 2,
    pairWith: "Burani Raita & Mirchi Salan",
    image: "/images/food/gosht-dum-biryani.jpg",
    tags: ["Awadhi Dum", "Kacchi Biryani"],
    available: true
  },
  {
    name: "Chicken Dum Biryani",
    description: "Layered aged Basmati rice with marinated chicken, mint, saffron, and aromatic spices.",
    category: "Food",
    subCategory: "rice-biryani",
    price: 365,
    dietary: "non-veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: true,
    spiciness: 2,
    pairWith: "Cucumber Raita",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
    tags: ["Dum Biryani", "Hyderabadi Style"],
    available: true
  },
  {
    name: "Prawns Dum Biryani",
    description: "Juicy coastal prawns layered with aged Basmati rice, caramelised onions, and fresh mint.",
    category: "Food",
    subCategory: "rice-biryani",
    price: 465,
    dietary: "non-veg",
    featured: false,
    isChefsSpecial: true,
    isGlutenFree: true,
    spiciness: 2,
    pairWith: "Burani Raita",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
    tags: ["Coastal Seafood", "Dum Rice"],
    available: true
  },
  {
    name: "Awadhi Mutton Yakhni Pulao",
    description: "Delicately spiced Basmati rice cooked in rich mutton bone marrow broth with mild whole spices.",
    category: "Food",
    subCategory: "rice-biryani",
    price: 425,
    dietary: "non-veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: true,
    spiciness: 1,
    pairWith: "Cucumber Mint Raita",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
    tags: ["Yakhni Pulao", "Awadhi Broth"],
    available: true
  },
  {
    name: "Subz Dum Biryani",
    description: "Seasonal garden vegetables and paneer dum-cooked with long-grain Basmati rice and rose water.",
    category: "Food",
    subCategory: "rice-biryani",
    price: 295,
    dietary: "veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: true,
    spiciness: 1,
    pairWith: "Mix Veg Raita",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
    tags: ["Vegetarian Biryani", "Aromatic"],
    available: true
  },
  {
    name: "Steamed Basmati / Jeera Rice",
    description: "Fluffy aged Basmati rice tempered with roasted cumin seeds and desi ghee.",
    category: "Food",
    subCategory: "rice-biryani",
    price: 185,
    dietary: "veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: true,
    spiciness: 0,
    pairWith: "Dal 1522 or Indian Curries",
    image: "https://images.unsplash.com/photo-1518013034458-30b0ee243591?auto=format&fit=crop&w=800&q=80",
    tags: ["Fragrant Rice", "Desi Ghee"],
    available: true
  },
  {
    name: "Peshawari Chole with Amritsari Kulcha",
    description: "Slow-simmered chickpeas infused with dried pomegranate seeds and roasted spices.",
    category: "Food",
    subCategory: "mains-indian",
    price: 425,
    dietary: "veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: false,
    spiciness: 2,
    pairWith: "Amritsari Kulcha",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=800&q=80",
    tags: ["Peshawari", "Amritsari"],
    available: true
  },
  {
    name: "Kadhai Paneer Dhaba Style",
    description: "Fresh cottage cheese tossed with pounded coriander seeds and crunchy bell peppers in rustic gravy.",
    category: "Food",
    subCategory: "mains-indian",
    price: 465,
    dietary: "veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: true,
    spiciness: 2,
    pairWith: "Garlic Naan",
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80",
    tags: ["Dhaba Style", "Paneer"],
    available: true
  },
  {
    name: "Vilayati Subz Panchmel",
    description: "Five garden-fresh vegetables tossed in rich tomato and cashew gravy with aromatic fenugreek.",
    category: "Food",
    subCategory: "mains-indian",
    price: 445,
    dietary: "veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: true,
    spiciness: 1,
    pairWith: "Laccha Paratha",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    tags: ["Vegetarian", "Cashew Gravy"],
    available: true
  },
  {
    name: "Elaneer Payasam (Tender Coconut Pudding)",
    description: "Silky South Indian payasam with tender coconut pulp, condensed milk, and cardamom.",
    category: "Food",
    subCategory: "desserts",
    price: 345,
    dietary: "veg",
    featured: false,
    isChefsSpecial: true,
    isGlutenFree: true,
    spiciness: 0,
    pairWith: "Dessert Wine",
    image: "https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=800&q=80",
    tags: ["Tender Coconut", "South Indian"],
    available: true
  },
  {
    name: "Gulab Jamun with Rabri & Gold Leaf",
    description: "Warm khoya dumplings soaked in saffron syrup, served over chilled saffron rabri.",
    category: "Food",
    subCategory: "desserts",
    price: 325,
    dietary: "veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: false,
    spiciness: 0,
    pairWith: "Chai or Espresso",
    image: "https://images.unsplash.com/photo-1579372786545-d24232daf58c?auto=format&fit=crop&w=800&q=80",
    tags: ["Heritage Sweet", "Saffron Rabri"],
    available: true
  },
  {
    name: "Warm Belgian Dark Chocolate Fondant",
    description: "Decadent molten 70% dark Belgian chocolate lava cake served with handcrafted Madagascar vanilla bean ice cream and berry coulis.",
    category: "Food",
    subCategory: "desserts",
    price: 395,
    dietary: "veg",
    featured: true,
    isChefsSpecial: true,
    isGlutenFree: false,
    spiciness: 0,
    pairWith: "Single Malt Whiskey or Espresso Martini",
    image: "https://images.unsplash.com/photo-1579372786545-d24232daf58c?auto=format&fit=crop&w=800&q=80",
    tags: ["Decadent", "Dessert Signature"],
    available: true
  },
  {
    name: "Saffron & Pistachio Tres Leches",
    description: "Airy sponge cake soaked in three artisanal milks infused with Kashmiri saffron, topped with whipped cream and crushed Iranian pistachios.",
    category: "Food",
    subCategory: "desserts",
    price: 425,
    dietary: "veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: false,
    spiciness: 0,
    pairWith: "Sparkling Prosecco",
    image: "https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=800&q=80",
    tags: ["Tres Leches", "Chef Special"],
    available: true
  },

  // COCKTAILS
  {
    name: "The 1522 Mumbai Skyline",
    description: "Aged bourbon infused with roasted cinnamon bark, fresh fig reduction, angostura bitters, served under a glass cloche filled with applewood smoke.",
    category: "Cocktails",
    subCategory: "craft-cocktails",
    price: 745,
    dietary: "veg",
    featured: true,
    isChefsSpecial: true,
    isGlutenFree: true,
    spiciness: 0,
    pairWith: "Mangalorean Ghee Roast or Lamb Sliders",
    image: "/images/drinks/smoked-cinnamon-old-fashioned.jpg",
    tags: ["Mixology Masterpiece", "Smoky & Bold"],
    available: true
  },
  {
    name: "Jamun & Botanical Gin Fizz",
    description: "Artisanal Indian gin muddled with fresh wild jamun pulp, kaffir lime leaves, elderflower liqueur, topped with tonic mist and pink Himalayan salt.",
    category: "Cocktails",
    subCategory: "craft-cocktails",
    price: 695,
    dietary: "veg",
    featured: true,
    isChefsSpecial: true,
    isGlutenFree: true,
    spiciness: 0,
    pairWith: "Truffle Edamame Dimsum",
    image: "/images/drinks/botanical-gin-fizz.jpg",
    tags: ["Rooftop Sunset", "Floral & Crisp"],
    available: true
  },
  {
    name: "Smoked Kokum & Tequila Picante",
    description: "100% Blue Agave Reposado tequila, artisanal kokum extract, bird's eye chili infusion, fresh pressed lime juice, agave nectar, and black salt rim.",
    category: "Cocktails",
    subCategory: "craft-cocktails",
    price: 725,
    dietary: "veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: true,
    spiciness: 1,
    pairWith: "Koliwada Prawns",
    image: "/images/drinks/smoked-rosemary-cocktail.jpg",
    tags: ["Spicy & Tangy", "Signature"],
    available: true
  },
  {
    name: "Cold Brew Espresso Martini",
    description: "Single-origin Chikmagalur dark roast cold brew, premium vanilla vodka, coffee liqueur, shaken with nitrogen foam and shaved dark cocoa.",
    category: "Cocktails",
    subCategory: "craft-cocktails",
    price: 675,
    dietary: "veg",
    featured: false,
    isChefsSpecial: false,
    isGlutenFree: true,
    spiciness: 0,
    pairWith: "Nutella Cheesecake",
    image: "/images/drinks/espresso-martini.jpg",
    tags: ["Nightcap", "Energizing"],
    available: true
  },

  // BEER
  {
    name: "Toit Tint-in-Wit / Basmati Blonde (Pint)",
    description: "Freshly tapped Belgian-style wheat beer with orange peel & coriander / Light aromatic blonde ale brewed fresh.",
    category: "Beer",
    subCategory: "craft-draught",
    price: 425,
    dietary: "veg",
    featured: true,
    available: true,
    image: "/images/drinks/craft-beer-tap.jpg",
    tags: ["Craft Draught", "On Tap"]
  },
  {
    name: "Gateway Brewing Co. White Zen",
    description: "Light, refreshing Hefeweizen with clove and banana notes brewed locally in Mumbai.",
    category: "Beer",
    subCategory: "craft-draught",
    price: 445,
    dietary: "veg",
    featured: false,
    available: true,
    image: "https://images.unsplash.com/photo-1535958636474-b021ee887b13?auto=format&fit=crop&w=800&q=80",
    tags: ["Craft Wheat", "Mumbai Local"]
  },
  {
    name: "Corona Extra / Stella Artois (Imported)",
    description: "Crisp international premium lagers served ice cold with fresh lime wedge.",
    category: "Beer",
    subCategory: "bottled",
    price: 495,
    dietary: "veg",
    featured: false,
    available: true,
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80",
    tags: ["Imported", "Pint"]
  },

  // WINE
  {
    name: "Sula Brut Tropicale Sparkling Reserve",
    description: "Premium Indian methode traditionnelle sparkling wine. Aromas of passion fruit, peach, and crisp effervescence. By the bottle.",
    category: "Wine",
    subCategory: "sparkling",
    price: 3800,
    dietary: "veg",
    featured: true,
    available: true,
    image: "https://images.unsplash.com/photo-1569919659476-f0852f6834b7?auto=format&fit=crop&w=800&q=80",
    tags: ["Sparkling", "Celebration"]
  },
  {
    name: "Grover La Reserve Cabernet Shiraz",
    description: "Aged in French oak barrels. Rich dark berries, chocolate, vanilla and smooth tannins.",
    category: "Wine",
    subCategory: "red-wine",
    price: 3200,
    dietary: "veg",
    featured: false,
    available: true,
    image: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=800&q=80",
    tags: ["Red Wine", "Oak Aged"]
  },
  {
    name: "Villa Antinori Toscana Bianco (Italy)",
    description: "Elegant aromas of citrus and white blossoms with a crisp mineral finish from Tuscany.",
    category: "Wine",
    subCategory: "white-wine",
    price: 4750,
    dietary: "veg",
    featured: false,
    available: true,
    image: "https://images.unsplash.com/photo-1584916201218-f4242ceb4809?auto=format&fit=crop&w=800&q=80",
    tags: ["Imported White", "Tuscany"]
  },

  // NON-ALCOHOLIC
  {
    name: "Kokum & Spiced Mint Cooler",
    description: "Fresh coastal kokum reduction, crushed garden mint, roasted cumin, rock salt, topped with sparkling water.",
    category: "Non-Alcoholic",
    subCategory: "mocktails",
    price: 325,
    dietary: "veg",
    featured: true,
    available: true,
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
    tags: ["House Cooler", "Refreshing"]
  },
  {
    name: "Lychee & Kaffir Lime Spritz",
    description: "Lush lychee puree, torn kaffir lime leaves, fresh pressed lemon juice, topped with elderflower tonic.",
    category: "Non-Alcoholic",
    subCategory: "mocktails",
    price: 345,
    dietary: "veg",
    featured: false,
    available: true,
    image: "https://images.unsplash.com/photo-1536935338788-846bb9981813?auto=format&fit=crop&w=800&q=80",
    tags: ["Zero Proof", "Botanical"]
  },
  {
    name: "Chikmagalur Artisan Cold Brew Coffee",
    description: "16-hour slow-steeped single-estate Arabica served over crystal clear ice with almond or dairy milk.",
    category: "Non-Alcoholic",
    subCategory: "cold-brew",
    price: 295,
    dietary: "veg",
    featured: false,
    available: true,
    image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=800&q=80",
    tags: ["Cold Brew", "Artisanal"]
  }
];

export const initialEvents = [
  {
    title: "Sunset Beats & Acoustic Rooftop Sessions",
    subtitle: "Golden Hour Melodies over Mumbai Skyline",
    artist: "Aarav & The Acoustic Collective",
    category: "Live Acoustic & Indie",
    genre: "Live Indie Acoustic & Pop Ballads",
    date: "Every Friday",
    day: "FRIDAY",
    time: "07:30 PM – 10:30 PM",
    timing: "07:30 PM – 10:30 PM",
    deck: "Upper Sky Deck (Open Air)",
    coverCharge: "Free Entry • Prior Table Reservation Recommended",
    description: "Unwind under the Mumbai evening sky as soulful acoustic guitars and warm vocals set the mood, paired with artisanal sundowner cocktails.",
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
    featured: true,
    highlight: true,
    active: true,
    rsvpCount: 48
  },
  {
    title: "Skyline Sundowner & Deep House DJ Set",
    subtitle: "High-Energy Weekend Rooftop Soundscape",
    artist: "DJ Shaan & Guest Percussionist",
    category: "Deep House & Melodic Techno",
    genre: "Melodic Techno, Afro House & Commercial Hits",
    date: "Every Saturday",
    day: "SATURDAY",
    time: "09:00 PM – 01:30 AM",
    timing: "09:00 PM – 01:30 AM",
    deck: "Upper Sky Deck & Main Bar",
    coverCharge: "Couples & Mixed Groups • Prior Table Booking Advised",
    description: "Elevate your weekend at Mumbai's premier rooftop party. Hypnotic basslines, live djembe percussion, and electrifying skyline lighting.",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80",
    featured: true,
    highlight: true,
    active: true,
    rsvpCount: 92
  },
  {
    title: "1522 Grand Rooftop Sunday Brunch",
    subtitle: "Live Cooking Stations, Unlimited Sangria & Chill Vibes",
    artist: "Rhythms of Cuba Trio",
    category: "Latin Jazz & Soul",
    genre: "Latin Jazz & Easy Listening",
    date: "Every Sunday",
    day: "SUNDAY",
    time: "12:30 PM – 04:30 PM",
    timing: "12:30 PM – 04:30 PM",
    deck: "Botanical Pergola & Sunset Cabanas",
    coverCharge: "₹1,899++ (Food) / ₹2,699++ (With Unlimited Cocktails & Beer)",
    description: "The ultimate leisurely Sunday. Live wood-fired pizzas, coastal barbecue grills, artisanal dim sum carts, and bottomless crafted cocktails.",
    image: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=800&q=80",
    featured: false,
    highlight: false,
    active: true,
    rsvpCount: 65
  },
  {
    title: "Retro Rock & Vinyl Thursdays",
    subtitle: "Classic 70s, 80s & 90s Rock Legends",
    artist: "DJ Brian & Resident Rock Selectors",
    category: "Classic Rock & Vinyl",
    genre: "Classic Rock, Grunge & Britpop",
    date: "Every Thursday",
    day: "THURSDAY",
    time: "08:00 PM – 12:00 AM",
    timing: "08:00 PM – 12:00 AM",
    deck: "Inner Rock Lounge & Bar",
    coverCharge: "Free Entry • 1+1 on Selected Single Malts till 9 PM",
    description: "Celebrating the true rock roots of 1522. Enjoy Queen, Led Zeppelin, Pink Floyd, and Nirvana over chilled craft brews and smoked platters.",
    image: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=800&q=80",
    featured: false,
    highlight: false,
    active: true,
    rsvpCount: 34
  }
];

export const initialOffers = [
  {
    title: "Sunset Golden Hours (4 PM – 7 PM)",
    subtitle: "1+1 on Craft Draught Beers & Select Gin Botanicals",
    description: "Catch Mumbai’s skyline as golden hour descends. Enjoy 1+1 on all local craft beer taps and signature botanical gin highballs on the Upper Sky Deck.",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-12-31'),
    active: true,
    badge: "Active Ritual",
    timing: "Monday to Friday • 04:00 PM – 07:00 PM",
    terms: "Valid on select beverages only. Cannot be clubbed with other corporate discounts."
  },
  {
    title: "The 1522 Grand Rooftop Sunday Brunch",
    subtitle: "Unlimited Live Wood-Fired Pizzas, Coastal Grills & Sangria",
    description: "Live acoustic Latin jazz trio, artisanal dim sum carts, freshly tossed wood-fired sourdough pizzas, and bottomless carafes of sangria and craft cocktails.",
    image: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=800&q=80",
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-12-31'),
    active: true,
    badge: "Every Sunday",
    timing: "Every Sunday • 12:30 PM – 04:30 PM",
    terms: "Packages start at ₹1,899++ (Food) / ₹2,699++ (Unlimited Alcohol). Prior booking advised."
  },
  {
    title: "Corporate Skyline Mixers & Deck Buyouts",
    subtitle: "Custom Beverage & Tapas Menus for 20 to 150 Guests",
    description: "Elevate your team dinners and client mixers with dedicated rooftop cabanas, personal bartenders, audio-visual presentation staging, and valet concierge.",
    image: "https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&w=800&q=80",
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-12-31'),
    active: true,
    badge: "Group Packages",
    timing: "All Days • Prior Inquiry Required",
    terms: "Tailored buffet & pass-around starter packages available upon request."
  }
];

export const initialGalleryItems = [
  // ==========================================
  // AMBIENCE — 8 CURATED IMAGES
  // ==========================================
  {
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
    title: "Open-Air Sky Deck Under Mumbai's Evening Skyline",
    category: "Ambience",
    alt: "1522 Mumbai Sky Deck Rooftop",
    featured: true,
    order: 1
  },
  {
    image: "https://images.unsplash.com/photo-1578474846511-04ba529f0b88?auto=format&fit=crop&w=1200&q=80",
    title: "Panoramic Rooftop Bar & High-Top Starlight Seating",
    category: "Ambience",
    alt: "Panoramic Rooftop Bar at 1522",
    featured: true,
    order: 2
  },
  {
    image: "https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&w=1200&q=80",
    title: "Warm Timber & Leather Heritage Pub Lounge",
    category: "Ambience",
    alt: "Stylish Pub Interior Lounge",
    featured: false,
    order: 3
  },
  {
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=80",
    title: "State-of-the-Art DJ Console & Soundscape Deck",
    category: "Ambience",
    alt: "DJ Booth with Professional Setup",
    featured: true,
    order: 4
  },
  {
    image: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?auto=format&fit=crop&w=1200&q=80",
    title: "Artisanal Marble Cocktail Counter & Crystal Stemware",
    category: "Ambience",
    alt: "Premium Cocktail Bar Counter",
    featured: true,
    order: 5
  },
  {
    image: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=1200&q=80",
    title: "Intimate Candlelit Dining Salon & Velvet Banquettes",
    category: "Ambience",
    alt: "Elegant Restaurant Seating Area",
    featured: false,
    order: 6
  },
  {
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1200&q=80",
    title: "Illuminated Spirit Reserves & Aged Whiskey Display",
    category: "Ambience",
    alt: "Bar Shelves and Atmospheric Lighting",
    featured: false,
    order: 7
  },
  {
    image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
    title: "Botanical Pergola Lounge & Sunset Cabanas",
    category: "Ambience",
    alt: "Wide Premium Rooftop Lounge Atmosphere",
    featured: false,
    order: 8
  },

  // ==========================================
  // FOOD & DRINK — 14 CURATED IMAGES
  // ==========================================
  {
    image: "/images/food/chicken-ghee-roast.jpg",
    title: "Mangalorean Chicken Ghee Roast with Soft Neer Dosa",
    category: "Food",
    alt: "Signature Chicken Ghee Roast",
    featured: true,
    order: 9
  },
  {
    image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=1200&q=80",
    title: "Coastal Malabar Fish Curry with Steamed Sannas",
    category: "Food",
    alt: "Premium Mangalorean Coastal Curry",
    featured: false,
    order: 10
  },
  {
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1200&q=80",
    title: "48-Hour Fermented Truffled Funghi & Fior di Latte Pizza",
    category: "Food",
    alt: "Artisan Wood-Fired Sourdough Pizza",
    featured: true,
    order: 11
  },
  {
    image: "/images/food/koliwada-prawns.png",
    title: "Arabian Sea Butter Garlic Tiger Prawns",
    category: "Food",
    alt: "Fresh Prawn Seafood Dish",
    featured: false,
    order: 12
  },
  {
    image: "https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?auto=format&fit=crop&w=1200&q=80",
    title: "Truffle Edamame & Charred Mushroom Dim Sum",
    category: "Food",
    alt: "Premium Vegetarian Crystal Dim Sum",
    featured: true,
    order: 13
  },
  {
    image: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=1200&q=80",
    title: "Charred Malai Paneer Tikka with Mint Coulis",
    category: "Food",
    alt: "Artisanal Restaurant Starter",
    featured: false,
    order: 14
  },
  {
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=1200&q=80",
    title: "Crispy Peri-Peri Chicken Tenders with Garlic Aioli",
    category: "Food",
    alt: "Crispy Chicken Starter",
    featured: false,
    order: 15
  },
  {
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=1200&q=80",
    title: "Golden Koliwada Calamari Rings with Spiced Tartar",
    category: "Food",
    alt: "Seafood Starter Crisp Calamari",
    featured: false,
    order: 16
  },
  {
    image: "/images/drinks/smoked-cinnamon-old-fashioned.jpg",
    title: "The 1522 Mumbai Skyline Smoked Fig Old Fashioned",
    category: "Drinks",
    alt: "Signature Smoked Cocktail",
    featured: true,
    order: 17
  },
  {
    image: "/images/drinks/botanical-gin-fizz.jpg",
    title: "Jamun & Botanical Gin Fizz with Pink Himalayan Rim",
    category: "Drinks",
    alt: "Colorful Botanical Cocktail",
    featured: true,
    order: 18
  },
  {
    image: "/images/drinks/smoked-rosemary-cocktail.jpg",
    title: "Artisanal Blood Orange & Elderflower Zero-Proof Spritz",
    category: "Drinks",
    alt: "Premium Zero-Proof Mocktail",
    featured: false,
    order: 19
  },
  {
    image: "/images/drinks/espresso-martini.jpg",
    title: "Handcrafted Cold Brew Nitrogen Espresso Martini",
    category: "Drinks",
    alt: "Cold Brew Espresso Martini with Coffee Beans",
    featured: true,
    order: 20
  },
  {
    image: "https://images.unsplash.com/photo-1579372786545-d24232daf58c?auto=format&fit=crop&w=1200&q=80",
    title: "Warm Belgian Dark Chocolate Fondant with Madagascar Vanilla",
    category: "Food",
    alt: "Decadent Restaurant Dessert",
    featured: false,
    order: 21
  },
  {
    image: "https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=1200&q=80",
    title: "Gourmet Tapas & Botanical Highball Table Presentation",
    category: "Drinks",
    alt: "Signature Food and Cocktail Presentation",
    featured: true,
    order: 22
  }
];

export const initialReviews = [
  {
    guestName: "Rohit Malhotra",
    rating: 5,
    deck: "Upper Sky Deck",
    comment: "The rooftop ambiance at Goldfinch Hotel is breathtaking. The Mangalorean Ghee Roast paired with their Mumbai Skyline cocktail was easily the highlight of our evening. Impeccable hospitality!",
    date: "August 2026",
    role: "Verified Dineout Guest"
  },
  {
    guestName: "Ananya Deshmukh",
    rating: 5,
    deck: "Sunset Cabanas",
    comment: "Celebrated my anniversary in the private cabana. The candlelit setup, attentive service by the team, and wood-fired truffled pizza made it an unforgettable night. Highly recommend booking in advance!",
    date: "July 2026",
    role: "Celebration Reservation"
  },
  {
    guestName: "Vikram Singhania",
    rating: 5,
    deck: "Botanical Pergola",
    comment: "Hosted a 45-guest corporate mixer here. From the custom bar menu to seamless AV setup and swift pass-around starters, 1522 executed everything with five-star precision.",
    date: "August 2026",
    role: "VP Marketing, Tech Innovations"
  }
];
